I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chap1.rpy", line 7, in script
    th "พวกเธอสองคนรู้ตัวรึเปล่า" with dissolve
Exception: Sayer 'th' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chap1.rpy", line 7, in script
    th "พวกเธอสองคนรู้ตัวรึเปล่า" with dissolve
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-8.0.3-sdk\renpy-8.0.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'th' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
renpy_framework 1.0
Tue May 27 01:24:17 2025
